### ISSUE TITLE
Make getAddresses without any params

### ISSUE THREAD

**Issue by EGreg** [Intercoin/CommunityContract#21]
It would return all roles and the addresses in all roles. Basically it would make a loop through all roles, and return the following array:

[
    addressesForRole0,
    addressesForRole1,
    addressesForRole2,
]

If a role index wasn't being used somehow, then send empty array of addresses for that role

[Also here](https://github.com/Intercoin/CommunityContract/blob/main/contracts/Community.sol#L437) please rename `rolesIndex` to `roleIndex` ... [also here rename](https://github.com/Intercoin/CommunityContract/blob/main/contracts/Community.sol#L473) to roleIndexes everywhere rename "rolesIndex" to "roleIndex" in the code

**Comment by EGreg** [comment]
You should probably modify `getAddresses(roles)` to return the above format, but in this case role0, role1 would not be the roles with index 0, 1 in *roles* array, but rather in the array passed

See if you use this format of getAddresses in any other repos, and then change the expected result from a single-dimensional array (concatenated basically) to a two-dimensional array.

Then duplicates look better, anyway.

**Comment by EGreg** [comment]
Example for getAddresses([2, 5, 7])   => [   [0x..., 0x....], [0x....], []  ]

**Comment by EGreg** [comment]
Also implement `getAddressesByRole(roleIndex, offset, limit)`

**Comment by artman325** [comment]
> If a role index wasn't being used somehow, then send empty array of addresses for that role

`getAddresses(uint8 rolesIndex)` replaced with `getAddresses(uint8[] calldata roleIndexes)` 
Also if roleIndexes is empty then need to use function signature getAddresses without paramaters like `getAddresses()`,
