### ISSUE TITLE
Change implementation of getRoles(addresses)

### ISSUE THREAD

**Issue by EGreg** [Intercoin/CommunityContract#24]
Just like getAddresses(roles) now should return an array of arrays, so should this method. It's much more useful that way, for my client-side code.

Basically the arrays should be in the same order as the addresses. So for example:

`getRoles(['0x123...', '0x294...', '0x928...'])`
would return this:
`[[0, 4], [], [2, 4, 5]`

Also change all calls to this function! Across all repos!

**Comment by artman325** [comment]
after investigation code in first look: seems need to check or/and update the following repos that using community(after task will be done):
- https://github.com/Intercoin/ControlContract
- https://github.com/Intercoin/VotingContract
- https://github.com/Intercoin/StakingContract

**Comment by artman325** [comment]
done
